### ISSUE TITLE
Save DP for later problem.

### ISSUE THREAD

**Issue by Noviandestroyer** [jmbowman/anima-character-generator#2]
When you save DP for later(At least with the "Save Generic DP for Later") option it works fine for one level then doubles. for example if on a 4 level character or creature I save 100 DP from level 2 it displays 200DP available for level 3 but then if I save 200 From level 3 it says i have 400DP remaining instead of 300. which would be the 200 I saved and the 100 for 4th level.

**Comment by Noviandestroyer** [comment]
Doesnt fix the problem. I still get a doubled ammount after saving it for a couple levels. exept it forgets the current levels DP. for example. in my test run i saved 600 DP from level 1, which correctly added to level 2's DP of 100 for 700 total. when I saved this 700 for level 3 it came up with the number 1400 which is double the previous saved amount. it seems however that with this flaw it should come out to 1500. 

Sorry about so many problem posts. i just want to help.

**Comment by jmbowman** [comment]
I found and fixed some lingering issues with the implementation yesterday, but they're mixed in with in-progress changes to handle varying screen sizes better; I'll try to get that wrapped up and checked in tonight, hopefully that'll fully fix it.

**Comment by jmbowman** [comment]
Also, I haven't updated the online built version yet; for now you'll have to download the code and run it locally to get the changes.  I'll update the version at http://jmbowman.github.io/anima-character-generator/ once I'm done with the responsive layout changes.

**Comment by jmbowman** [comment]
Ok, the online version is updated now.  Also made a lot of tweaks to handle various screen sizes better (involving an upgrade to Bootstrap 3); think everything still works at least as well as before, but let me know if you find any problems.
