### ISSUE TITLE
not really an issue with the input window

### ISSUE THREAD

**Issue by ZHRhub** [jmbowman/anima-character-generator#5]
this generator is awesome and has saved tons of time! i use it on several devices, but i have found that while on my smart phone, the only issue i have is that when you go to make a selection or do anything else with the input window, its static nature keeps you from moving it. this is a problem because it keeps the lower right section out of the screen frame with out the ability to move it. if there is any way this window could become dynamic or movable, i feel it would add a huge layer to user friendly behavior across multiple platform devices.

**Comment by jmbowman** [comment]
I just finished a major revamp of the layout to use Bootstrap 3 and support various screen sizes appropriately; let me know if you still have problems with the new version.
